// "SSC" | "HSC 1st Year" | "HSC 2nd Year" | "Diploma" | "Graduate"
// "Home" | "School" | "College" | "University" | "Private Coaching"
// "Male" | "Female" | "Any"
export const CIRCULARS = [
  {
    id: 171009,
    title: "Need bangla medium tutor",
    salary: 3500,
    standard: "HSC 1st Year",
    subjects: ["Accounting", "Finance", "Production Management", "Marketing"],
    location: {
      area: "Amlapara",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 3, gender: "male" },
    createdAt: "2024-06-05",
  },
  {
    id: 171010,
    title: "Need english medium tutor",
    salary: 6000,
    standard: "Class 8",
    subjects: ["Bangla", "English"],
    location: {
      area: "Sarada Ghosh Road",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 4, gender: "female" },
    createdAt: "2024-07-20",
  },
  {
    id: 171011,
    title: "Need english medium tutor",
    salary: 3000,
    standard: "SSC",
    subjects: ["Mathematics"],
    location: {
      area: "Boro Kalibari Road",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 3, gender: "any" },
    createdAt: "2024-08-01",
  },
  {
    id: 171012,
    title: "Need bangla medium tutor",
    salary: 7000,
    standard: "SSC",
    subjects: ["Physic", "Chemistry", "Biology"],
    location: {
      area: "Boro Bazar",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 5, gender: "female" },
    createdAt: "2024-09-10",
  },
  {
    id: 171013,
    title: "Need english medium tutor",
    salary: 4500,
    standard: "SSC",
    subjects: ["Mathematics", "Higher Math"],
    location: {
      area: "Choto bazar",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 3, gender: "female" },
    createdAt: "2024-10-15",
  },
  {
    id: 171014,
    title: "Need english medium tutor",
    salary: 3500,
    standard: "HSC 1st Year",
    subjects: ["English 1st", "English 2nd"],
    location: {
      area: "Charpara",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Private Coaching",
    preferences: { days: 6, gender: "any" },
    createdAt: "2024-11-07",
  },
  {
    id: 171015,
    title: "Need bangla medium tutor",
    salary: 6000,
    standard: "HSC 1st Year",
    subjects: ["Accounting", "Finance", "Production Management", "Marketing"],
    location: {
      area: "Kachijuly Road",
      city: "Mymensingh",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 4, gender: "any" },
    createdAt: "2024-12-14",
  },
  {
    id: 171016,
    title: "Need bangla medium tutor",
    salary: 5000,
    standard: "HSC 1st Year",
    subjects: ["Accounting", "Finance", "Production Management", "Marketing"],
    location: {
      area: "Mirpur 1",
      city: "Dhaka",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 3, gender: "any" },
    createdAt: "2025-01-02",
  },
  {
    id: 171017,
    title: "Need bangla medium tutor",
    salary: 3500,
    standard: "HSC 1st Year",
    subjects: ["Accounting", "Finance", "Production Management", "Marketing"],
    location: {
      area: "Gulshan 5",
      city: "Dhaka",
      country: "Bangladesh",
    },
    institution: "Private Coaching",
    preferences: { days: 6, gender: "male" },
    createdAt: "2025-03-06",
  },
  {
    id: 171018,
    title: "Need bangla medium tutor",
    salary: 5500,
    standard: "HSC 1st Year",
    subjects: ["Accounting", "Finance", "Production Management", "Marketing"],
    location: {
      area: "Mohakhali",
      city: "Dhaka",
      country: "Bangladesh",
    },
    institution: "Home",
    preferences: { days: 3, gender: "female" },
    createdAt: "2025-04-15",
  },
];
